#!/bin/bash

# User specific environment
# if ! [[ "$PATH" =~ "${HOME}/.local/bin" ]]; then
#     export PATH="${HOME}/.local/bin:${PATH}"
# fi

# Set XDG home directories
# export XDG_CACHE_HOME="${HOME}/.cache"
# export XDG_CONFIG_HOME="${HOME}/.config"
# export XDG_DATA_HOME="${HOME}/.local/share"
# export XDG_STATE_HOME="${HOME}/.local/state"

bash_config_dir="${HOME}/.config/bash"
bashrc_dir="${bash_config_dir}/bashrc.d"

# User specific bashrc.d
if [[ -d ${bashrc_dir} ]]; then
        for rc in ${bashrc_dir}/* ; do
                if [[ -f "$rc" ]]; then
                        source "$rc"
                fi
        done
        unset rc
fi

# Host specific bashrc.d
bashrc_dir_self="${bash_config_dir}/self.d"
if [[ -d ${bashrc_dir_self} ]]; then
        for rc in ${bashrc_dir_self}/* ; do
                if [[ -f "$rc" ]]; then
                        source "$rc"
                fi
        done
        unset rc
fi

unset bash_config_dir
unset bashrc_dir
unset bashrc_dir_self
