#!/bin/bash

RESET="\033[0m"

BOLD_BLUE="\033[1;34m"
BOLD_MAGENTA="\033[1;35m"
BLUE="\033[34m"
BOLD_RED="\033[1;31m"
BOLD_YELLOW="\033[1;33m"
GREEN="\033[32m"

git_dirty () {
    if [[ "$(git status 2> /dev/null | tail -n 1)" != "nothing to commit"* ]]; then
        echo "*"
    else
        echo " "
    fi
}

git_current_branch () {
    # branch="$(git branch --no-color 2> /dev/null | awk '/^\* /{print substr($0, 3)}')"
	branch="$(git branch --show-current 2> /dev/null)"
    if [[ "$branch" == "("*")" ]]; then
        branch="detached:$(git name-rev --name-only HEAD 2> /dev/null)"
    elif [[ ! -z "$branch" ]]; then
        branch="$(echo "$branch" | awk '{printf "%s", substr($0, 1, 16); if (length($0) > 16) printf ".."}')"
    fi
    echo "${branch}"
}

git_prompt_color () {
    local git_dirty=$(git_dirty)
	local branch="$(git_current_branch)"

	if [[ "${branch}" == "main" || "${branch}" == "master" ]]; then
		echo -en "${BOLD_RED}"
	elif [[ "${branch}" = detached* || "${git_dirty}" == "*" ]]; then
		echo -en "${BOLD_YELLOW}"
	elif [[ "${branch}" == "develop" ]]; then
		echo -en "${BOLD_MAGENTA}"
	else
		echo -en "${GREEN}"
	fi
}

git_prompt () {
    local git_dirty=$(git_dirty)
	local branch="$(git_current_branch)"

	if [[ ! -z "${branch}" ]]; then
		echo -n " (${branch} ${git_dirty})"
	fi
}

aws_vault_prompt () {
	local vault="${AWS_VAULT}"
	if [[ ! -z "${vault}" ]]; then
		echo -en "${BOLD_YELLOW}"
		echo -n " [AWS ${vault}]"
	fi
}

user="${USER}"
if [[ "${user}" == "ericelsken" ]]; then
	user=me
fi

hostname="${HOSTNAME}"
if [[ "${hostname}" == "localhost.localdomain" || ${hostname} == "fedora" ]]; then
	hostname=here
fi

userhostname_color="${BLUE}"
if [[ "${user}" != "me" || "${hostname}" != "here" ]]; then
	userhostname_color="${BOLD_MAGENTA}"
fi

PS1="\[${RESET}\]"
PS1+="\[${userhostname_color}\]"
PS1+="[${user}@${hostname}]"
PS1+="\[${RESET}\] "
PS1+="\[${BOLD_BLUE}\]\W"
PS1+="\[${RESET}\]"
PS1+="\[\$(git_prompt_color)\]"
PS1+="\$(git_prompt)"
# PS1+="\[${RESET}\]"
# PS1+="\[\$(aws_vault_prompt)\]"
PS1+="\[${RESET}\] "
PS1+="\[${BOLD_BLUE}\]\$"
PS1+="\[${RESET}\] "

