#!/bin/bash

alias e="${EDITOR}"

alias myip="curl https://httpbin.org/ip 2> /dev/null | jq -r .origin"

alias gbclear="git branch --merged | egrep -v '(^\*|main|develop|master)' | xargs git branch -d"

alias dfg='git --git-dir=${HOME}/.config/dotfiles --work-tree=${HOME}'

alias la='ls -la'

